#!/usr/bin/env python3
"""Generate the Swift glass tokens from design-tokens/glass.tokens.json.

The JSON file is the one source for the glass design system's values. This
script writes them as Swift constants for the native macOS app:

    macos/Sources/TCDesign/Generated/GlassTokens.swift

Run it after editing the JSON:

    python3 scripts/design-tokens/generate.py

`--check` exits non-zero if the Swift file is out of date instead of
writing it. The Swift suite also guards drift: TCDesignTests decodes the
JSON and compares every token with the generated constants.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SOURCE = REPO / "design-tokens" / "glass.tokens.json"
OUTPUT = REPO / "macos" / "Sources" / "TCDesign" / "Generated" / "GlassTokens.swift"

WEIGHTS = {"regular", "medium", "semibold", "bold", "heavy"}
DESIGNS = {"default", "monospaced"}
# macOS text styles and their sizes at the default system text size. A type
# step names its style and states that size, so the scale follows the system
# setting the way the rest of the shell does (see TC.Font_ in the app).
TEXT_STYLES = {
    "largeTitle": 26,
    "title": 22,
    "title2": 17,
    "title3": 15,
    "headline": 13,
    "body": 13,
    "callout": 12,
    "subheadline": 11,
    "footnote": 10,
    "caption": 10,
    "caption2": 10,
}
IDENTIFIER = re.compile(r"^[a-z][A-Za-z0-9]*$")


class TokenError(ValueError):
    pass


def identifier(name: str, where: str) -> str:
    if not IDENTIFIER.match(name):
        raise TokenError(f"{where}: {name!r} is not a lowerCamelCase identifier")
    return name


def rgb(value: str, where: str) -> str:
    if not re.fullmatch(r"#[0-9a-fA-F]{6}", value):
        raise TokenError(f"{where}: {value!r} is not #rrggbb")
    return "0x" + value[1:].upper()


def number(value: object, where: str) -> str:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise TokenError(f"{where}: {value!r} is not a number")
    text = repr(float(value))
    return text[:-2] if text.endswith(".0") else text


def alpha(entry: dict, where: str) -> str:
    value = entry.get("alpha", 1)
    if isinstance(value, bool) or not isinstance(value, (int, float)) or not 0 <= value <= 1:
        raise TokenError(f"{where}: alpha {value!r} is not in 0...1")
    return number(value, where)


def doc(note: str | None, indent: str) -> list[str]:
    return [f"{indent}/// {note}"] if note else []


def color_expr(entry: dict, where: str) -> str:
    return f"GlassRGBA({rgb(entry['hex'], where)}, alpha: {alpha(entry, where)})"


def render(tokens: dict) -> str:
    if tokens.get("version") != 1:
        raise TokenError("version: expected 1")
    out: list[str] = [
        "// GENERATED by scripts/design-tokens/generate.py from",
        "// design-tokens/glass.tokens.json. Do not edit; edit the JSON and",
        "// regenerate. TCDesignTests fails if this file and the JSON disagree.",
        "",
        "import CoreGraphics",
        "",
        "// swiftlint:disable all",
        "",
        "/// The glass design system's values: dark only, purple brand, SF Pro.",
        "public enum GlassTokens {",
    ]

    def section(name: str, kind: str, items: list[tuple[str, str, str | None]]) -> None:
        out.append(f"    public enum {name} {{")
        for key, expr, note in items:
            out.extend(doc(note, "        "))
            out.append(f"        public static let {key}: {kind} = {expr}")
        out.append("")
        out.append(f"        /// Every {name.lower()} token by its JSON name.")
        out.append(f"        public static let all: [String: {kind}] = [")
        for key, _, _ in items:
            out.append(f'            "{key}": {key},')
        out.append("        ]")
        out.append("    }")
        out.append("")

    colors = []
    for key, entry in tokens["color"].items():
        where = f"color.{key}"
        colors.append((identifier(key, where), color_expr(entry, where), entry.get("note")))
    section("Color", "GlassRGBA", colors)

    gradients = []
    for key, entry in tokens["gradient"].items():
        where = f"gradient.{key}"
        stops = ", ".join(
            f"GlassStop({rgb(stop['hex'], where)}, alpha: {alpha(stop, where)}, at: {number(stop['at'], where)})"
            for stop in entry["stops"]
        )
        gradients.append(
            (identifier(key, where), f"GlassGradient(angle: {number(entry['angle'], where)}, stops: [{stops}])", None)
        )
    section("Gradient", "GlassGradient", gradients)

    shadows = []
    for key, layers in tokens["shadow"].items():
        where = f"shadow.{key}"
        parts = []
        for layer in layers:
            parts.append(
                "GlassShadow("
                f"x: {number(layer.get('x', 0), where)}, "
                f"y: {number(layer.get('y', 0), where)}, "
                f"blur: {number(layer.get('blur', 0), where)}, "
                f"color: GlassRGBA({rgb(layer['hex'], where)}, alpha: {alpha(layer, where)}), "
                f"inset: {'true' if layer.get('inset') else 'false'})"
            )
        shadows.append((identifier(key, where), "[" + ", ".join(parts) + "]", None))
    section("Shadow", "[GlassShadow]", shadows)

    for name, json_key in (("Radius", "radius"), ("Space", "space"), ("Size", "size"), ("Opacity", "opacity"), ("Motion", "motion")):
        kind = "Double" if name in ("Opacity", "Motion") else "CGFloat"
        items = [
            (identifier(key, f"{json_key}.{key}"), number(value, f"{json_key}.{key}"), None)
            for key, value in tokens[json_key].items()
        ]
        section(name, kind, items)

    types = []
    for key, entry in tokens["type"].items():
        where = f"type.{key}"
        weight = entry.get("weight", "regular")
        design = entry.get("design", "default")
        if weight not in WEIGHTS:
            raise TokenError(f"{where}: weight {weight!r}")
        if design not in DESIGNS:
            raise TokenError(f"{where}: design {design!r}")
        style = entry.get("textStyle")
        if style not in TEXT_STYLES:
            raise TokenError(f"{where}: textStyle {style!r}")
        if number(entry["size"], where) != str(TEXT_STYLES[style]):
            raise TokenError(f"{where}: size {entry['size']} is not {style}'s {TEXT_STYLES[style]}")
        types.append(
            (
                identifier(key, where),
                "GlassTypeStyle("
                f"textStyle: .{style}, "
                f"size: {number(entry['size'], where)}, "
                f"weight: .{weight}, "
                f"lineHeight: {number(entry['lineHeight'], where)}, "
                f"tracking: {number(entry.get('tracking', 0), where)}, "
                f"design: .{design}, "
                f"uppercase: {'true' if entry.get('uppercase') else 'false'}, "
                f"tabular: {'true' if entry.get('tabular') else 'false'})",
                None,
            )
        )
    section("TypeScale", "GlassTypeStyle", types)

    out[-1:] = ["}", ""]
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="fail if the Swift file is stale")
    args = parser.parse_args()
    try:
        swift = render(json.loads(SOURCE.read_text()))
    except (TokenError, KeyError, json.JSONDecodeError) as error:
        print(f"glass tokens: {error}", file=sys.stderr)
        return 2
    if args.check:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != swift:
            print(f"{OUTPUT.relative_to(REPO)} is stale; run scripts/design-tokens/generate.py", file=sys.stderr)
            return 1
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(swift)
    print(f"wrote {OUTPUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
