// Copyright (C) 2026 K&Z Partners LLC
// SPDX-License-Identifier: AGPL-3.0-or-later

//! The attested-key drift probe: the ed25519 half of the attestation drill,
//! and an observation tool only.
//!
//! [`super::drill`] fetches the report with `signing_algo=ecdsa`, derives one
//! signing address out of it, and joins that address to a receipt it paid for.
//! That is the right shape for the gateway, and it is the wrong report for
//! everything the client already does: NEAR AI signs each hosted model's
//! receipts with a **per-model** ed25519 key that appears only in
//! the report's model-attestation container, and only when it was asked for with
//! `signing_algo=ed25519`. This probe fetches that report and derives those
//! keys, so the path a future invite-free contribution flow would depend on is
//! exercised on a schedule before anything is switched on.
//!
//! **It admits nothing.** No caller may treat a passed step here as
//! permission. It performs no completion, spends nothing, writes nothing, and
//! its whole output is counts, labels, public register values and digests.
//!
//! # What it actually establishes, and what it does not
//!
//! - The nonce is **generated by this verifier** ([`DrillNonceSource`]) and
//!   never read back out of the report. A nonce the other side chose proves
//!   nothing, and `request_nonce` in the response is the other side's echo of
//!   ours -- so the binding checked is `report_data == signing_address ||
//!   nonce` for the value this process picked.
//! - [`trace_commons_attestation::receipt::attested_ed25519_key`] reads
//!   `report_data` out of the entry's own `intel_quote` at the fixed v4 TDX
//!   offset. It **parses**; it does not verify. So this probe re-checks the
//!   same binding against a **DCAP-verified** quote at
//!   [`AttestedKeyDriftStep::ModelKeyInVerifiedQuote`]. Until that step, a
//!   derived key is TLS-grade trust in whoever answered.
//! - **No measurement distinguishes which model a key serves.** In the
//!   committed captures both model enclaves carry identical MRTD, MRCONFIGID
//!   and RTMR0..3, and `report_data` is `key || nonce` and nothing else.
//!   Nothing here should be read as binding a key to a model; the only thing
//!   that names the model is the `model_name` field beside the entry, which
//!   the provider writes.
//!
//! # Drift, not a single red light
//!
//! Running this on a schedule is worth something only if two runs can be
//! *compared* and the difference named. [`compare_attested_key_drift`] reports
//! a key rotation, a measurement move, a TCB change and a quote-verification
//! regression as **separate** findings, because they send an operator to three
//! different places. Collapsing them into "the drill went red" is the failure
//! mode this exists to avoid.

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use trace_commons_attestation::receipt::{
    AttestedKeyError, gateway_ed25519_key, model_attestation_entries, model_ed25519_keys,
};

use super::client::{AttestationClientError, AttestedKeyReportClient};
use super::measurements::{
    EXPECTED_MEASUREMENTS_CONTROL, ExpectedMeasurements, MeasurementField, MeasurementVerdict,
    check_measurements_opt,
};
use super::quote::{QuoteVerifyError, VerifiedQuote, verify_quote};

/// The TCB verdict the probe accepts. Anything else is reported by name.
///
/// Same value and same reasoning as [`super::drill::REQUIRED_TCB_STATUS`]:
/// deliberately not configurable, because a configurable allow-list is the
/// lever that turns a red probe green without fixing anything.
pub const REQUIRED_TCB_STATUS: &str = super::drill::REQUIRED_TCB_STATUS;

/// A step of the probe, in run order.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AttestedKeyDriftStep {
    /// The endpoint served an `signing_algo=ed25519` report for our nonce.
    ReportFetched,
    /// `gateway_attestation` binds a key to the nonce we generated.
    GatewayKeyBound,
    /// The model-attestation container binds at least one key for our model to that
    /// nonce.
    ModelKeysBound,
    /// Every model entry's own quote verified against Intel collateral
    /// fetched for that quote.
    ModelQuoteVerified,
    /// Intel's TCB verdict for the model platform is [`REQUIRED_TCB_STATUS`].
    ModelTcbUpToDate,
    /// The derived key and our nonce are in the **verified** quote's report
    /// data, not merely in the JSON the endpoint sent.
    ModelKeyInVerifiedQuote,
    /// Every pinned measurement register matched the model quote.
    ModelMeasurementsPinned,
}

impl AttestedKeyDriftStep {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::ReportFetched => "report_fetched",
            Self::GatewayKeyBound => "gateway_key_bound",
            Self::ModelKeysBound => "model_keys_bound",
            Self::ModelQuoteVerified => "model_quote_verified",
            Self::ModelTcbUpToDate => "model_tcb_up_to_date",
            Self::ModelKeyInVerifiedQuote => "model_key_in_verified_quote",
            Self::ModelMeasurementsPinned => "model_measurements_pinned",
        }
    }

    /// Every step, in run order.
    pub const ALL: [AttestedKeyDriftStep; 7] = [
        Self::ReportFetched,
        Self::GatewayKeyBound,
        Self::ModelKeysBound,
        Self::ModelQuoteVerified,
        Self::ModelTcbUpToDate,
        Self::ModelKeyInVerifiedQuote,
        Self::ModelMeasurementsPinned,
    ];
}

/// How a step ended. `NotRun` is deliberately not `Passed`; see
/// [`super::drill::NearAttestationStepStatus`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum AttestedKeyDriftStatus {
    Passed,
    Failed,
    NotRun,
}

/// One step's outcome. A stable label, never a message.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AttestedKeyDriftStepResult {
    pub step: AttestedKeyDriftStep,
    pub status: AttestedKeyDriftStatus,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub missing_control: Option<String>,
}

/// Whether the credential this deployment already holds is accepted by the
/// report endpoint.
///
/// This is an *answer*, not a diagnosis: the probe cannot tell an unset key
/// from a wrong one, only that the endpoint refused authorization. It exists
/// because "does our existing API key reach the report endpoint, or does that
/// need a different credential" is otherwise unanswerable without a live run.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ReportCredentialVerdict {
    /// The endpoint served the report with the credential we sent.
    Accepted,
    /// The endpoint answered 401 or 403.
    Unauthorized,
    /// The call failed for some other reason, so it says nothing either way.
    Inconclusive,
}

/// What the model quote carried, once verified. Registers are public image
/// identifiers and appear in full, exactly as in [`super::drill`].
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AttestedKeyQuoteEvidence {
    pub tcb_status: String,
    pub advisory_ids: Vec<String>,
    pub mrtd: String,
    pub mr_config_id: String,
    pub rtmr: [String; 4],
}

/// What the measurement check saw. Same shape as the ECDSA drill's.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AttestedKeyMeasurementEvidence {
    /// `pinned`, `mismatch`, or `refused`.
    pub verdict: String,
    pub checked_fields: Vec<String>,
    pub mismatched_fields: Vec<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub missing_control: Option<String>,
}

/// The probe's full result: the thing a scheduled run stores and the next run
/// compares against.
///
/// Keys appear only as digests. The nonce appears in full because this process
/// generated it and put it in a query string. Register values appear in full
/// because they are public image identifiers and a mismatch is useless without
/// them.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AttestedKeyDriftOutcome {
    /// The nonce **we** generated.
    pub nonce: String,
    /// The model asked about. A routing label, not a secret.
    pub model_label: String,
    /// True only when every step passed.
    pub passed: bool,
    pub steps: Vec<AttestedKeyDriftStepResult>,
    pub credential: ReportCredentialVerdict,
    /// Digest of the gateway key. Never the key.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub gateway_key_ref: Option<String>,
    /// Digests of the per-model keys, in the order the report listed them.
    pub model_key_refs: Vec<String>,
    /// How many entries named this model. More than one means the model is
    /// served by several enclaves.
    pub model_entry_count: usize,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub quote: Option<AttestedKeyQuoteEvidence>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub measurements: Option<AttestedKeyMeasurementEvidence>,
}

impl AttestedKeyDriftOutcome {
    /// The steps that did not pass, named. Empty exactly when `passed`.
    pub fn blocking_steps(&self) -> Vec<String> {
        self.steps
            .iter()
            .filter(|result| result.status != AttestedKeyDriftStatus::Passed)
            .map(|result| match &result.reason {
                Some(reason) => format!("{}:{reason}", result.step.as_str()),
                None => result.step.as_str().to_string(),
            })
            .collect()
    }
}

/// A `sha256:`-prefixed digest, for values that must never appear in full.
fn secret_ref(value: &str) -> String {
    format!("sha256:{}", hex::encode(Sha256::digest(value.as_bytes())))
}

/// Where the nonce comes from.
///
/// A trait, not a `&str` parameter, because the probe's central claim is that
/// **it** chose the nonce. A caller-supplied nonce would let the thing being
/// observed pick its own challenge, one indirection later. Tests substitute a
/// fixed source; production uses [`RandomNonce`].
pub trait DrillNonceSource: Send + Sync {
    /// A fresh 64-hex-character nonce.
    fn nonce(&self) -> String;
}

/// The production nonce source: 32 fresh random bytes per run.
pub struct RandomNonce;

impl DrillNonceSource for RandomNonce {
    fn nonce(&self) -> String {
        super::drill::generate_drill_nonce()
    }
}

/// Accumulates step results so a probe that stops early still renders every
/// step, with the ones it never reached marked `NotRun`.
///
/// Deliberately a second copy of [`super::drill`]'s log rather than a shared
/// generic one: the two drills have different step sets, and the shape that
/// would let them share is a trait over the step enum, which buys nothing but
/// couples a change to one drill's steps to the other's compile.
struct StepLog {
    results: Vec<AttestedKeyDriftStepResult>,
}

impl StepLog {
    fn new() -> Self {
        Self {
            results: Vec::new(),
        }
    }

    fn pass(&mut self, step: AttestedKeyDriftStep) {
        self.results.push(AttestedKeyDriftStepResult {
            step,
            status: AttestedKeyDriftStatus::Passed,
            reason: None,
            missing_control: None,
        });
    }

    fn fail(&mut self, step: AttestedKeyDriftStep, reason: impl Into<String>) {
        self.results.push(AttestedKeyDriftStepResult {
            step,
            status: AttestedKeyDriftStatus::Failed,
            reason: Some(reason.into()),
            missing_control: None,
        });
    }

    fn fail_missing_control(&mut self, step: AttestedKeyDriftStep, control: &str) {
        self.results.push(AttestedKeyDriftStepResult {
            step,
            status: AttestedKeyDriftStatus::Failed,
            reason: Some(format!("missing_control:{control}")),
            missing_control: Some(control.to_string()),
        });
    }

    fn fail_client(&mut self, step: AttestedKeyDriftStep, error: &AttestationClientError) {
        match error.missing_control() {
            Some(control) => self.fail_missing_control(step, control),
            None => self.fail(step, error.code()),
        }
    }

    fn finish(mut self) -> Vec<AttestedKeyDriftStepResult> {
        let seen: Vec<AttestedKeyDriftStep> =
            self.results.iter().map(|result| result.step).collect();
        for step in AttestedKeyDriftStep::ALL {
            if !seen.contains(&step) {
                self.results.push(AttestedKeyDriftStepResult {
                    step,
                    status: AttestedKeyDriftStatus::NotRun,
                    reason: None,
                    missing_control: None,
                });
            }
        }
        self.results.sort_by_key(|result| position_of(result.step));
        self.results
    }
}

fn position_of(step: AttestedKeyDriftStep) -> usize {
    AttestedKeyDriftStep::ALL
        .iter()
        .position(|candidate| *candidate == step)
        .expect("ALL contains every step")
}

/// A stable label for a key-derivation failure. The condition, never a
/// message: an error string from this area would carry keys and nonces.
fn key_error_label(error: AttestedKeyError) -> &'static str {
    match error {
        AttestedKeyError::Malformed => "report_shape",
        AttestedKeyError::NotEd25519 => "not_ed25519",
        AttestedKeyError::NonceMismatch => "nonce_mismatch",
        AttestedKeyError::ReportDataMismatch => "report_data_mismatch",
        AttestedKeyError::KeyMalformed => "key_malformed",
        AttestedKeyError::ModelNotAttested => "model_not_attested",
        AttestedKeyError::SignatureKindUnrecognised => "signature_kind_unrecognised",
    }
}

/// A stable label for a quote-verification failure.
fn quote_error_label(error: &QuoteVerifyError) -> &'static str {
    match error {
        QuoteVerifyError::CollateralMalformed { .. } => "collateral_malformed",
        QuoteVerifyError::VerificationFailed { .. } => "verification_failed",
        QuoteVerifyError::NotTdx => "not_tdx",
    }
}

/// The credential answer implied by a report fetch.
fn credential_verdict(error: &AttestationClientError) -> ReportCredentialVerdict {
    match error {
        AttestationClientError::HttpStatus { status, .. } if *status == 401 || *status == 403 => {
            ReportCredentialVerdict::Unauthorized
        }
        _ => ReportCredentialVerdict::Inconclusive,
    }
}

/// The `intel_quote` bytes of every entry in `report_json` naming `model`.
///
/// An entry for this model that carries no readable quote is an error, not a
/// skip: skipping it would leave the probe verifying some other entry's quote
/// and reporting a green step for a key it never checked.
fn model_entry_quotes(report_json: &str, model: &str) -> Result<Vec<Vec<u8>>, &'static str> {
    let document: serde_json::Value =
        serde_json::from_str(report_json).map_err(|_| "report_shape")?;
    // Whichever container this deployment serves the entries under. Reading
    // one name here while `model_ed25519_keys` read the other is how the
    // probe came to report a green key step beside an unverifiable quote.
    let entries = model_attestation_entries(&document).ok_or("report_shape")?;
    let mut quotes = Vec::new();
    for entry in entries {
        if entry.get("model_name").and_then(serde_json::Value::as_str) != Some(model) {
            continue;
        }
        let hex_quote = entry
            .get("intel_quote")
            .and_then(serde_json::Value::as_str)
            .ok_or("model_entry_has_no_quote")?;
        quotes.push(hex::decode(hex_quote).map_err(|_| "model_entry_quote_not_hex")?);
    }
    if quotes.is_empty() {
        return Err("model_not_attested");
    }
    Ok(quotes)
}

/// The `(key, nonce)` a verified quote's report data commits to, in the
/// ed25519 layout.
///
/// The key is 32 bytes, so it fills `report_data[0..32]` with no zero padding
/// to discriminate on -- unlike the ECDSA layout, where the 20-byte address
/// leaves `[20..32]` zero and that padding is what
/// [`super::drill::attested_signer_address`] asserts. The nonce is `[32..64]`.
///
/// `None` for report data that is not 64 bytes. `VerifiedQuote::report_data`
/// is built from TDReport10's `[u8; 64]` today, but this is a `&[u8]` read and
/// a length assumption here would be a panic rather than a named failure.
fn verified_key_and_nonce(verified: &VerifiedQuote) -> Option<(String, String)> {
    let key = verified.report_data.get(0..32)?;
    let nonce = verified.report_data.get(32..64)?;
    Some((hex::encode(key), hex::encode(nonce)))
}

fn measurement_evidence(verdict: &MeasurementVerdict) -> AttestedKeyMeasurementEvidence {
    let names = |fields: &[MeasurementField]| -> Vec<String> {
        fields.iter().map(|f| f.as_str().to_string()).collect()
    };
    match verdict {
        MeasurementVerdict::Pinned { fields } => AttestedKeyMeasurementEvidence {
            verdict: "pinned".to_string(),
            checked_fields: names(fields),
            mismatched_fields: Vec::new(),
            missing_control: None,
        },
        MeasurementVerdict::Mismatch { fields, mismatches } => AttestedKeyMeasurementEvidence {
            verdict: "mismatch".to_string(),
            checked_fields: names(fields),
            mismatched_fields: names(&mismatches.iter().map(|m| m.field).collect::<Vec<_>>()),
            missing_control: None,
        },
        MeasurementVerdict::Refused { control } => AttestedKeyMeasurementEvidence {
            verdict: "refused".to_string(),
            checked_fields: Vec::new(),
            mismatched_fields: Vec::new(),
            missing_control: Some((*control).to_string()),
        },
    }
}

/// Run the probe.
///
/// `now_unix` is the clock the collateral is evaluated against; production
/// passes wall-clock time and it is a parameter only so a captured fixture can
/// be pinned to its capture date.
///
/// Nothing here admits, charges or writes. Every failure is a named label on a
/// step, and a probe that could not reach a step reports it as `NotRun` rather
/// than as a pass.
pub async fn run_attested_key_drift_drill(
    client: &dyn AttestedKeyReportClient,
    expected: Option<&ExpectedMeasurements>,
    nonce_source: &dyn DrillNonceSource,
    now_unix: u64,
) -> AttestedKeyDriftOutcome {
    let nonce = nonce_source.nonce();
    let mut log = StepLog::new();
    let mut outcome = AttestedKeyDriftOutcome {
        nonce: nonce.clone(),
        model_label: client.model().to_string(),
        passed: false,
        steps: Vec::new(),
        credential: ReportCredentialVerdict::Inconclusive,
        gateway_key_ref: None,
        model_key_refs: Vec::new(),
        model_entry_count: 0,
        quote: None,
        measurements: None,
    };

    // A nonce that is not 64 hex characters cannot bind anything, and sending
    // it would produce a report this probe would then have to interpret.
    // Refuse before the network call.
    if nonce.len() != 64 || !nonce.bytes().all(|b| b.is_ascii_hexdigit()) {
        log.fail(
            AttestedKeyDriftStep::ReportFetched,
            "nonce_source_malformed",
        );
        return finish(outcome, log);
    }

    // 1. The ed25519 report, for the nonce we generated.
    let report_json = match client.fetch_ed25519_report_json(&nonce).await {
        Ok(body) => {
            outcome.credential = ReportCredentialVerdict::Accepted;
            log.pass(AttestedKeyDriftStep::ReportFetched);
            body
        }
        Err(error) => {
            outcome.credential = credential_verdict(&error);
            log.fail_client(AttestedKeyDriftStep::ReportFetched, &error);
            return finish(outcome, log);
        }
    };

    // 2. The gateway key. Recorded and checked, but it is not the key a
    //    hosted-model receipt is signed with, so a failure here does not stop
    //    the model half -- the two rotate independently and the whole point is
    //    to see which moved.
    match gateway_ed25519_key(&report_json, &nonce) {
        Ok(key) => {
            outcome.gateway_key_ref = Some(secret_ref(&key));
            log.pass(AttestedKeyDriftStep::GatewayKeyBound);
        }
        Err(error) => log.fail(
            AttestedKeyDriftStep::GatewayKeyBound,
            key_error_label(error),
        ),
    }

    // 3. The per-model keys. This is the set a `provider_tee` receipt's signer
    //    must be checked against, and the reason this probe fetches a
    //    different report than `super::drill` does.
    let model_keys = match model_ed25519_keys(&report_json, &nonce, client.model()) {
        Ok(keys) => {
            outcome.model_key_refs = keys.iter().map(|key| secret_ref(key)).collect();
            outcome.model_entry_count = keys.len();
            log.pass(AttestedKeyDriftStep::ModelKeysBound);
            keys
        }
        Err(error) => {
            log.fail(AttestedKeyDriftStep::ModelKeysBound, key_error_label(error));
            return finish(outcome, log);
        }
    };

    // 4. The model quotes, against Intel collateral fetched **per quote**.
    //    Collateral is platform-specific: the gateway's does not verify a
    //    model enclave's quote, which is measured in this module's tests.
    let quotes = match model_entry_quotes(&report_json, client.model()) {
        Ok(quotes) => quotes,
        Err(label) => {
            log.fail(AttestedKeyDriftStep::ModelQuoteVerified, label);
            return finish(outcome, log);
        }
    };
    let mut verified_quotes: Vec<VerifiedQuote> = Vec::new();
    for quote in &quotes {
        let collateral = match client.fetch_collateral_for(quote).await {
            Ok(collateral) => collateral,
            Err(error) => {
                log.fail_client(AttestedKeyDriftStep::ModelQuoteVerified, &error);
                return finish(outcome, log);
            }
        };
        match verify_quote(quote, &collateral, now_unix) {
            Ok(verified) => verified_quotes.push(verified),
            Err(error) => {
                log.fail(
                    AttestedKeyDriftStep::ModelQuoteVerified,
                    quote_error_label(&error),
                );
                return finish(outcome, log);
            }
        }
    }
    log.pass(AttestedKeyDriftStep::ModelQuoteVerified);

    // Evidence comes from the first verified model enclave. Where a model is
    // served by several, the rest are still verified above; only one set of
    // registers is rendered, and `model_entry_count` says how many there were.
    let first = verified_quotes
        .first()
        .expect("a non-empty quote list yields a verified quote");
    outcome.quote = Some(AttestedKeyQuoteEvidence {
        tcb_status: first.tcb_status.clone(),
        advisory_ids: first.advisory_ids.clone(),
        mrtd: first.mrtd.clone(),
        mr_config_id: first.mr_config_id.clone(),
        rtmr: first.rtmr.clone(),
    });

    // 5. Intel's TCB verdict. Policy, named -- see `super::drill`.
    let unexpected: Vec<&str> = verified_quotes
        .iter()
        .map(|verified| verified.tcb_status.as_str())
        .filter(|status| *status != REQUIRED_TCB_STATUS)
        .collect();
    match unexpected.first() {
        None => log.pass(AttestedKeyDriftStep::ModelTcbUpToDate),
        Some(status) => log.fail(
            AttestedKeyDriftStep::ModelTcbUpToDate,
            format!("tcb_status:{status}"),
        ),
    }

    // 6. The binding, re-checked against the **verified** quote.
    //
    //    Step 3 already checked it, but it checked a quote nobody had verified
    //    -- `attested_ed25519_key` reads report_data at a fixed offset out of
    //    bytes the endpoint sent. Only here is the key one that Intel-rooted
    //    hardware committed to, alongside a nonce this process chose.
    //
    //    The comparison is over **sets**, not a positional zip. Two separate
    //    walks of the report produced the keys and the quotes, and a zip would
    //    quietly truncate if they ever disagreed about which entries count --
    //    which is exactly the divergence worth catching, and the one a
    //    dropped `model_name` filter produces.
    let mut derived: Vec<String> = Vec::with_capacity(verified_quotes.len());
    let mut layout_unreadable = false;
    let mut nonce_wrong = false;
    for verified in &verified_quotes {
        match verified_key_and_nonce(verified) {
            Some((key, bound_nonce)) => {
                if bound_nonce != nonce.to_ascii_lowercase() {
                    nonce_wrong = true;
                }
                derived.push(key);
            }
            None => layout_unreadable = true,
        }
    }
    let mut claimed: Vec<String> = model_keys
        .iter()
        .map(|key| key.to_ascii_lowercase())
        .collect();
    derived.sort();
    claimed.sort();
    if layout_unreadable {
        log.fail(
            AttestedKeyDriftStep::ModelKeyInVerifiedQuote,
            "verified_report_data_too_short",
        );
    } else if nonce_wrong {
        log.fail(
            AttestedKeyDriftStep::ModelKeyInVerifiedQuote,
            "verified_report_data_binds_another_nonce",
        );
    } else if derived != claimed {
        log.fail(
            AttestedKeyDriftStep::ModelKeyInVerifiedQuote,
            "verified_report_data_binds_another_key",
        );
    } else {
        log.pass(AttestedKeyDriftStep::ModelKeyInVerifiedQuote);
    }

    // 7. The pinned measurements, against the first model enclave's quote.
    let verdict = check_measurements_opt(expected, first, EXPECTED_MEASUREMENTS_CONTROL);
    outcome.measurements = Some(measurement_evidence(&verdict));
    match &verdict {
        MeasurementVerdict::Pinned { .. } => {
            log.pass(AttestedKeyDriftStep::ModelMeasurementsPinned)
        }
        MeasurementVerdict::Mismatch { mismatches, .. } => {
            let fields: Vec<&str> = mismatches.iter().map(|m| m.field.as_str()).collect();
            log.fail(
                AttestedKeyDriftStep::ModelMeasurementsPinned,
                format!("mismatch:{}", fields.join(",")),
            );
        }
        MeasurementVerdict::Refused { control } => {
            log.fail_missing_control(AttestedKeyDriftStep::ModelMeasurementsPinned, control);
        }
    }

    finish(outcome, log)
}

fn finish(mut outcome: AttestedKeyDriftOutcome, log: StepLog) -> AttestedKeyDriftOutcome {
    outcome.steps = log.finish();
    outcome.passed = outcome
        .steps
        .iter()
        .all(|result| result.status == AttestedKeyDriftStatus::Passed);
    outcome
}

/// One difference between two runs of the probe.
///
/// Separate variants, not one `Changed` label, because the three things this
/// probe is watching for send an operator to three different places: a
/// rotation is NEAR AI re-keying, a measurement move is a redeployed image,
/// and a verification regression is either an expired collateral window or
/// something worse.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "drift", rename_all = "snake_case")]
pub enum AttestedKeyDrift {
    /// The report could not be fetched this time but could before.
    ReportUnavailable,
    /// The endpoint stopped accepting the credential it accepted before.
    CredentialRejected,
    /// The gateway key is not the one the previous run saw.
    GatewayKeyRotated,
    /// The per-model key set is not the one the previous run saw.
    ModelKeysRotated,
    /// The number of enclaves serving the model changed.
    ModelEntryCountChanged { before: usize, after: usize },
    /// A measurement register moved. One finding per register.
    MeasurementMoved { field: String },
    /// Intel's verdict for the platform changed.
    TcbStatusChanged { before: String, after: String },
    /// The quote verified before and does not now.
    QuoteVerificationRegressed,
    /// The quote did not verify before and does now.
    QuoteVerificationRecovered,
}

/// Compare two runs and name every difference.
///
/// `before` is the earlier run. The comparison is deliberately over the
/// evidence a run stores -- digests, register values, counts and step statuses
/// -- so a scheduled probe needs to keep nothing but its last outcome, and no
/// key is retained anywhere to make the comparison.
///
/// Two runs against **different models** are not comparable and yield no
/// findings beyond the model label mismatch, which is why `model_label`
/// disagreement short-circuits: reporting "the keys rotated" for two different
/// models would be exactly wrong, since per-model keys differ per model by
/// design.
pub fn compare_attested_key_drift(
    before: &AttestedKeyDriftOutcome,
    after: &AttestedKeyDriftOutcome,
) -> Vec<AttestedKeyDrift> {
    if before.model_label != after.model_label {
        return Vec::new();
    }
    let mut findings = Vec::new();

    let fetched = |outcome: &AttestedKeyDriftOutcome| {
        step_status(outcome, AttestedKeyDriftStep::ReportFetched) == AttestedKeyDriftStatus::Passed
    };
    if fetched(before) && !fetched(after) {
        findings.push(AttestedKeyDrift::ReportUnavailable);
    }
    if before.credential == ReportCredentialVerdict::Accepted
        && after.credential == ReportCredentialVerdict::Unauthorized
    {
        findings.push(AttestedKeyDrift::CredentialRejected);
    }

    // An absent key on either side is not a rotation: it is the fetch or the
    // derivation having failed, which the step statuses already say. Comparing
    // `Some(k)` against `None` here would report a rotation that did not
    // happen, on the run where the probe learned the least.
    if let (Some(a), Some(b)) = (&before.gateway_key_ref, &after.gateway_key_ref) {
        if a != b {
            findings.push(AttestedKeyDrift::GatewayKeyRotated);
        }
    }
    if !before.model_key_refs.is_empty()
        && !after.model_key_refs.is_empty()
        && before.model_key_refs != after.model_key_refs
    {
        findings.push(AttestedKeyDrift::ModelKeysRotated);
    }
    if before.model_entry_count != after.model_entry_count
        && before.model_entry_count != 0
        && after.model_entry_count != 0
    {
        findings.push(AttestedKeyDrift::ModelEntryCountChanged {
            before: before.model_entry_count,
            after: after.model_entry_count,
        });
    }

    let verified = |outcome: &AttestedKeyDriftOutcome| {
        step_status(outcome, AttestedKeyDriftStep::ModelQuoteVerified)
            == AttestedKeyDriftStatus::Passed
    };
    match (verified(before), verified(after)) {
        (true, false) => findings.push(AttestedKeyDrift::QuoteVerificationRegressed),
        (false, true) => findings.push(AttestedKeyDrift::QuoteVerificationRecovered),
        _ => {}
    }

    if let (Some(a), Some(b)) = (&before.quote, &after.quote) {
        for (field, old, new) in [
            ("mrtd", &a.mrtd, &b.mrtd),
            ("mrconfigid", &a.mr_config_id, &b.mr_config_id),
            ("rtmr0", &a.rtmr[0], &b.rtmr[0]),
            ("rtmr1", &a.rtmr[1], &b.rtmr[1]),
            ("rtmr2", &a.rtmr[2], &b.rtmr[2]),
            ("rtmr3", &a.rtmr[3], &b.rtmr[3]),
        ] {
            if old != new {
                findings.push(AttestedKeyDrift::MeasurementMoved {
                    field: field.to_string(),
                });
            }
        }
        if a.tcb_status != b.tcb_status {
            findings.push(AttestedKeyDrift::TcbStatusChanged {
                before: a.tcb_status.clone(),
                after: b.tcb_status.clone(),
            });
        }
    }

    findings
}

fn step_status(
    outcome: &AttestedKeyDriftOutcome,
    step: AttestedKeyDriftStep,
) -> AttestedKeyDriftStatus {
    outcome
        .steps
        .iter()
        .find(|result| result.step == step)
        .map(|result| result.status)
        .unwrap_or(AttestedKeyDriftStatus::NotRun)
}

#[cfg(test)]
#[path = "key_drift_tests.rs"]
mod tests;
