//! Shared wording for every managed-session shell.
pub fn copy() -> serde_json::Value {
    serde_json::from_str(r#"{
            "title": "Managed sessions",
            "description": "Choose a saved account for each new session. Standard sessions can keep running alongside it.",
            "launch": "Launch managed session",
            "add": "Add account",
            "refresh": "Refresh",
            "terminal_scope": "App launches open in {destination}. CLI launches stay in their current terminal.",
            "terminal_unavailable": "Terminal launch is unavailable in this build. Use near-ai in your terminal.",
            "empty": "No managed sessions yet.",
            "sign_in": "Sign in",
            "exit_code": "Exit code: {code}",
            "dismiss": "Dismiss",
            "connecting": "Connecting to managed sessions…",
            "retry": "Retry",
            "rename": "Rename account",
            "label": "Account label",
            "save": "Save",
            "cancel": "Cancel",
            "remove_question": "Remove saved account?",
            "remove": "Remove account",
            "remove_description": "This removes the saved credentials and isolated profile from this computer.",
            "manage": "Manage",
            "default": "Default",
            "use_default": "Use as default",
            "rename_short": "Rename",
            "reconnect": "Sign in / reconnect",
            "verify": "Verify account",
            "near_ai": "NEAR AI",
            "api_key": "API key",
            "subscription": "Subscription",
            "save_title": "Save an account",
            "tool": "Tool",
            "claude": "Claude Code",
            "codex": "Codex",
            "connection": "Connection",
            "label_placeholder": "Label, such as Personal or Work",
            "login_description": "Sign in through the native tool in Terminal. Repeat Add account to save another subscription.",
            "key_storage": "The key is stored in the operating system credential store.",
            "save_login": "Save and sign in",
            "save_account": "Save account",
            "saved_account": "Saved account",
            "choose_account": "Choose account",
            "project_placeholder": "Choose a project folder",
            "choose_folder": "Choose folder",
            "launch_scope": "Opens in {destination}. This selection applies to this launch.",
            "launch_short": "Launch",
            "terminal": "your terminal",
            "global_title": "Change global settings",
            "global_scope": "Changes below affect standard sessions after restarting the tool.",
            "launch_unknown": "Refresh sessions before retrying.",
            "action_failed": "Managed action failed."
    }"#).expect("static managed copy is valid JSON")
}
