pub(crate) mod compute;
pub(crate) mod consent;
pub(crate) mod daemon;
pub(crate) mod history;
pub(crate) mod insights;
pub(crate) mod mission_drafts;
pub(crate) mod native_flows;
pub(crate) mod platform;
pub(crate) mod privacy;
pub(crate) mod private_ai;
pub(crate) mod profile;
pub(crate) mod routing;
pub(crate) mod settings;
pub(crate) mod witness;

pub(crate) fn handler<R: tauri::Runtime>()
-> impl Fn(tauri::ipc::Invoke<R>) -> bool + Send + Sync + 'static {
    tauri::generate_handler![
        daemon::core_status,
        daemon::retry_daemon_startup,
        daemon::queue_outcome_line,
        daemon::residual_secret_line,
        daemon::redaction_summary_copy,
        daemon::project_ignore_copy,
        daemon::arming_offer_copy,
        daemon::attestation_copy,
        daemon::certificate_copy,
        daemon::eligibility_copy,
        daemon::eligibility_group_copy,
        daemon::daemon_call,
        daemon::preview_entry,
        daemon::dismiss_entry,
        daemon::approve_entry,
        daemon::approve_project,
        profile::publish_profile,
        profile::withdraw_profile,
        daemon::pause_daemon,
        daemon::resume_daemon,
        daemon::arming_suggestion,
        daemon::accept_arming,
        daemon::decline_arming,
        daemon::cancel_entry,
        daemon::cancel_project,
        daemon::preview_body,
        daemon::preview_turns,
        daemon::search_original,
        settings::set_quiescence_minutes,
        settings::set_approval_hold_seconds,
        settings::set_digest_hours,
        settings::set_max_uploads_per_day,
        settings::set_max_bytes_per_day_mb,
        witness::witness_status,
        witness::configure_witness,
        witness::clear_witness,
        routing::discover_routing,
        routing::configure_routing,
        routing::probe_routing,
        routing::probe_routed_tools,
        consent::consent_options,
        consent::scrubber_pattern_names,
        consent::enroll_with_invite,
        consent::set_consent_scopes,
        consent::acknowledge_near_ai_notice,
        consent::grant_void_notice,
        consent::acknowledge_grant_voids,
        privacy::set_private_inference,
        privacy::set_inference_evidence,
        privacy::set_token_contribution,
        privacy::set_token_capture,
        privacy::token_storage_status,
        privacy::clean_token_storage,
        settings::set_source_declaration,
        settings::set_project_mode,
        settings::list_projects,
        settings::list_audit,
        private_ai::start_private_ai_credential,
        private_ai::private_ai_credential_status,
        private_ai::private_ai_balance,
        private_ai::private_ai_funding,
        private_ai::private_ai_harnesses,
        private_ai::plan_harness,
        private_ai::commit_harness,
        platform::open_external_url,
        platform::platform_capabilities,
        platform::notification_permission,
        platform::request_notification_permission,
        platform::set_start_at_login,
        platform::open_system_settings,
        platform::quit_app,
        platform::quit_confirmation_copy,
        private_ai::cancel_private_ai_credential,
        private_ai::forget_private_ai_credential,
        native_flows::native_wallet_flow,
        native_flows::contributor_disclosure_copy,
        native_flows::witness_review_copy,
        native_flows::automatic_contribution_copy,
        native_flows::near_ai_account_enroll,
        native_flows::prepare_admission_session,
        native_flows::witness_preview_support,
        native_flows::witness_preview_request,
        history::history_detail,
        history::request_history_refresh,
        history::account_session_status,
        history::account_sign_in,
        history::withdrawal_confirmation_prompt,
        history::withdraw_history,
        history::validate_public_run_editor,
        history::publish_public_run,
        history::unpublish_public_run,
        history::skill_learning_copy,
        history::skill_candidate,
        history::skill_review,
        history::skill_evaluate,
        history::skill_install_plan,
        history::skill_install_commit,
        history::skill_install_status,
        history::skill_install_rollback,
        insights::insights_list,
        insights::insights_summary,
        insights::analyze_insight,
        insights::explain_insight,
        insights::delete_insight,
        insights::annotate_insight,
        insights::clear_insight_annotation,
        insights::link_test_report,
        insights::link_git_insight,
        insights::unlink_insight_evidence,
        platform::pick_directory,
        platform::consume_deep_link,
        platform::open_native_wallet_url,
        platform::open_account_sign_in_url,
        insights::insights_question_cards,
        insights::insights_episode_list,
        insights::insights_episode_create,
        insights::insights_episode_explain,
        insights::insights_episode_annotate,
        insights::insights_episode_clear_assessment,
        insights::insights_episode_delete,
        insights::comparisons::comparison_task_create,
        insights::comparisons::comparison_task_list,
        insights::comparisons::comparison_task_explain,
        insights::comparisons::comparison_task_replace_episodes,
        insights::comparisons::comparison_task_set_context,
        insights::comparisons::comparison_task_set_outcome,
        insights::comparisons::comparison_task_clear_outcome,
        insights::comparisons::comparison_task_reconfirm,
        insights::comparisons::comparison_specification_list,
        insights::comparisons::comparison_specification_preview,
        insights::comparisons::comparison_specification_save,
        insights::comparisons::comparison_specification_evaluate,
        mission_drafts::mission_draft_list,
        mission_drafts::mission_draft_show,
        mission_drafts::mission_draft_import,
        mission_drafts::mission_draft_delete,
        compute::compute_status,
        compute::enable_compute,
        compute::resume_compute,
        compute::pause_compute,
        compute::disable_compute
    ]
}
