#!/usr/bin/env bash
# Generate the MSIX tile PNGs that Package.appxmanifest declares.
#
# The three files this writes were, before this script existed, solid squares
# of #315FBA: one unique pixel each, no mark on them at all. They were the
# right dimensions with the right filenames in the right brand colour, so every
# automated check passed and the Start menu showed a flat rectangle.
#
# # Why this runs on macOS and not on the Windows runner
#
# The design spec's plan was to rasterize through MarkRaster, the C#
# rasterizer already in TraceCommons.Interop, on windows-latest. That is still
# the better long-term home: it keeps the Windows raster path in the Windows
# toolchain, and MarkRaster is deliberately built to run off-Windows so its
# geometry is testable anywhere.
#
# It is not what this does, because it could not be verified from here. This
# repository pins .NET SDK 8.0.100 in windows/global.json and the development
# machine has 10.0.400, so nothing under windows/ builds or tests locally at
# all. Writing a C# rasterizer path and a PowerShell driver that nobody could
# run would be exactly the kind of plausible, unexercised artwork pipeline that
# produced the solid squares.
#
# So the tiles are generated by the same CoreGraphics renderer that draws the
# macOS icon, from the same geometry JSON, and committed. That makes
# regeneration a macOS task, which is a real limitation and is why the
# committed files are not covered by the assets/mark drift check: reproducing
# them needs a Mac, and the check runs on ubuntu-latest.
set -euo pipefail

cd "$(dirname "$0")/../.."
GEOMETRY="${1:-assets/mark/geometry.json}"
ASSETS="${2:-windows/packaging/Assets}"

if [ ! -f "$GEOMETRY" ]; then
  echo "FATAL: $GEOMETRY does not exist." >&2
  echo "Generate it: cargo run -p trace-commons-mark --bin mark-export" >&2
  exit 1
fi

if ! command -v swift >/dev/null 2>&1; then
  echo "FATAL: swift is not available; these tiles can only be regenerated on macOS." >&2
  echo "See the comment at the top of this script for why." >&2
  exit 1
fi

mkdir -p "$ASSETS"

# Exactly the three assets Package.appxmanifest names, at the sizes its
# filenames promise. Scale-qualified (.scale-200) and targetsize variants are
# NOT generated: MSIX resolves those by filename convention through makepri,
# and no part of that packaging path can be exercised here, so they are left
# for whoever can run the Windows build rather than guessed at.
swift macos/scripts/render-mark.swift "$GEOMETRY" light framed \
  "50:$ASSETS/StoreLogo.png" \
  "150:$ASSETS/Square150x150Logo.png" \
  "44:$ASSETS/Square44x44Logo.png"

for tile in StoreLogo.png Square150x150Logo.png Square44x44Logo.png; do
  if [ ! -s "$ASSETS/$tile" ]; then
    echo "FATAL: the renderer produced no output for $tile" >&2
    exit 1
  fi
  echo "wrote $ASSETS/$tile"
done
