// GENERATED by scripts/design-tokens/generate.py from
// design-tokens/glass.tokens.json. Do not edit; edit the JSON and
// regenerate. `generate.py --check` fails in CI if this file and the
// JSON disagree.

//! The brand accent and the text-safe status colours, from the glass
//! design tokens. `style.rs` maps the shell's `tc_*` palette onto
//! these; cairo drawing reads the constants, since GTK offers no
//! supported way to read a `@define-color` back out of a provider.

/// The light scheme.
pub mod light {
    /// `purple`.
    pub const ACCENT: &str = "#6D14F3";
    /// `purple`.
    pub const ACCENT_LINE: &str = "#6D14F3";
    /// `purpleText`.
    pub const ACCENT_TEXT: &str = "#5B10CC";
    /// `textOnAccent`.
    pub const ON_ACCENT: &str = "#FFFFFF";
    /// `statusOn`.
    pub const STATUS_ON: &str = "#1A8F4C";
    /// `statusOnText`.
    pub const STATUS_ON_TEXT: &str = "#11613A";
    /// `statusAsk`.
    pub const STATUS_ASK: &str = "#A8690F";
    /// `statusAskText`.
    pub const STATUS_ASK_TEXT: &str = "#7A4A06";
    /// `statusOutside`.
    pub const STATUS_OUTSIDE: &str = "#D0342C";
    /// `statusOutsideText`.
    pub const STATUS_OUTSIDE_TEXT: &str = "#A3221C";
    /// `textOnStatus`.
    pub const ON_STATUS: &str = "#0C0C0E";
}

/// The dark scheme.
pub mod dark {
    /// `purpleSoft`.
    pub const ACCENT: &str = "#8A3DFF";
    /// `purpleText`.
    pub const ACCENT_LINE: &str = "#C9B3FF";
    /// `purpleText`.
    pub const ACCENT_TEXT: &str = "#C9B3FF";
    /// `textOnAccent`.
    pub const ON_ACCENT: &str = "#FFFFFF";
    /// `statusOn`.
    pub const STATUS_ON: &str = "#3DDC84";
    /// `statusOnText`.
    pub const STATUS_ON_TEXT: &str = "#3DDC84";
    /// `statusAsk`.
    pub const STATUS_ASK: &str = "#F5C142";
    /// `statusAskText`.
    pub const STATUS_ASK_TEXT: &str = "#F5C142";
    /// `statusOutside`.
    pub const STATUS_OUTSIDE: &str = "#FF6B6B";
    /// `statusOutsideText`.
    pub const STATUS_OUTSIDE_TEXT: &str = "#FF6B6B";
    /// `textOnStatus`.
    pub const ON_STATUS: &str = "#0C0C0E";
}

/// The light roles as GTK `@define-color` rules, loaded ahead of
/// the shell's own palette, which refers to them by name.
pub const LIGHT_CSS: &str = r#"
@define-color tc_accent #6D14F3; /* purple */
@define-color tc_accent_line #6D14F3; /* purple */
@define-color tc_accent_text #5B10CC; /* purpleText */
@define-color tc_on_accent #FFFFFF; /* textOnAccent */
@define-color tc_status_on #1A8F4C; /* statusOn */
@define-color tc_status_on_text #11613A; /* statusOnText */
@define-color tc_status_ask #A8690F; /* statusAsk */
@define-color tc_status_ask_text #7A4A06; /* statusAskText */
@define-color tc_status_outside #D0342C; /* statusOutside */
@define-color tc_status_outside_text #A3221C; /* statusOutsideText */
@define-color tc_on_status #0C0C0E; /* textOnStatus */
"#;

/// The dark roles as GTK `@define-color` rules, loaded ahead of
/// the shell's own palette, which refers to them by name.
pub const DARK_CSS: &str = r#"
@define-color tc_accent #8A3DFF; /* purpleSoft */
@define-color tc_accent_line #C9B3FF; /* purpleText */
@define-color tc_accent_text #C9B3FF; /* purpleText */
@define-color tc_on_accent #FFFFFF; /* textOnAccent */
@define-color tc_status_on #3DDC84; /* statusOn */
@define-color tc_status_on_text #3DDC84; /* statusOnText */
@define-color tc_status_ask #F5C142; /* statusAsk */
@define-color tc_status_ask_text #F5C142; /* statusAskText */
@define-color tc_status_outside #FF6B6B; /* statusOutside */
@define-color tc_status_outside_text #FF6B6B; /* statusOutsideText */
@define-color tc_on_status #0C0C0E; /* textOnStatus */
"#;
