/* trace_commons.h -- C ABI for the trace-commons-contributor background
 * daemon.
 *
 * This is the surface a native application shell (SwiftUI on macOS, WinUI
 * on Windows, GTK on Linux) links against to host the daemon loop
 * in-process instead of shipping a second signed binary. It is generated by
 * hand to match `crates/trace-commons-contributor-ffi/src/lib.rs`
 * (`#[unsafe(no_mangle)] pub unsafe extern "C" fn ...`) exactly; keep the
 * two in sync when either changes.
 *
 * OWNERSHIP RULE, stated once, enforced everywhere in this header: every
 * `char*` RETURNED by this library is owned by the caller and freed with
 * `tc_string_free`. Every `const char*` is BORROWED and valid only until
 * the handle that owns it (`tc_handle*` or `tc_preview*`) is freed. There
 * is no other lifetime rule anywhere in this API.
 *
 * Every function here catches Rust panics at the boundary and converts them
 * to an ordinary error; a panic never unwinds into the caller. Every
 * pointer parameter is null-checked; passing NULL produces an error, not a
 * crash. No path, token, URL, or trace content ever appears in a string
 * this library returns -- fixed labels only, the same discipline the
 * daemon's socket already applies.
 */

#ifndef TRACE_COMMONS_H
#define TRACE_COMMONS_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Opaque handle to a running daemon, returned by tc_daemon_start. */
typedef struct tc_handle tc_handle;

/* Opaque handle to one open preview, returned by tc_preview_open. */
typedef struct tc_preview tc_preview;

/* Lifecycle. Runs the daemon loop on its own thread with its own runtime.
 *
 * Returns NULL and sets *err (if err is non-NULL) on failure -- most
 * notably when another daemon already holds daemon.lock for this
 * config_dir. A second tc_daemon_start against the same directory must
 * fail rather than let two loops race the same on-disk queue. *err, on
 * failure, is an owned string; free it with tc_string_free.
 */
tc_handle*  tc_daemon_start(const char* config_dir, char** err);

/* Stop the daemon loop and free the handle. Safe to call with NULL. */
void        tc_daemon_stop(tc_handle*);

/* Control. Same request handlers the socket serves, called in-process.
 *
 * Returns a NUL-terminated JSON response; free with tc_string_free. Never
 * returns NULL: a bad handle, method, or params_json produces a JSON error
 * frame (`{"error":{"code":"bad_params",...}}`) rather than a null pointer.
 */
char*       tc_call(tc_handle*, const char* method, const char* params_json);

/* Events. cb is invoked on a background thread with a JSON event frame
 * each time the daemon publishes one, until the daemon is stopped. The
 * `event_json` pointer passed to cb is borrowed for the duration of that
 * one call only; do not retain it. ctx is passed back unchanged.
 */
void        tc_subscribe(tc_handle*, void (*cb)(const char* event_json, void* ctx), void* ctx);

/* Preview. Reads the session file and runs the real redaction pipeline.
 *
 * tc_preview_open returns NULL and sets *err (if err is non-NULL) on
 * failure -- most commonly an unknown entry_id. On success, everything
 * returned by the tc_preview_* accessors below is borrowed and valid until
 * tc_preview_free.
 */
tc_preview* tc_preview_open(tc_handle*, const char* entry_id, char** err);
const char* tc_preview_body(tc_preview*);          /* redacted transcript, UTF-8 */
const char* tc_preview_summary_json(tc_preview*);  /* counts, sizes, opening prompt */

/* Search the redacted body for needle, a local in-memory scan. Returns the
 * number of matches, or -1 on error. On success, *matches_json is set to
 * an owned JSON array of byte offsets; free with tc_string_free. On error,
 * *matches_json (if non-NULL) is set to NULL -- there is nothing to free.
 */
int32_t     tc_preview_search(tc_preview*, const char* needle, char** matches_json);

void        tc_preview_free(tc_preview*);

/* Free a string returned by this library. Safe to call with NULL. This is
 * the only valid way to free a char* this library returns.
 */
void        tc_string_free(char*);

/* The last error recorded on the calling thread, or NULL if none has been
 * recorded yet. Borrowed: valid until the next call, on this same thread,
 * to any function in this library that records a new error. Do not free
 * the returned pointer.
 */
const char* tc_last_error(void);

#ifdef __cplusplus
}
#endif

#endif /* TRACE_COMMONS_H */
