/* trace_commons.h -- C ABI for the trace-commons-contributor background
 * daemon.
 *
 * This is the surface a native application shell (SwiftUI on macOS, WinUI
 * on Windows, GTK on Linux) links against to host the daemon loop
 * in-process instead of shipping a second signed binary. It is generated by
 * hand to match `crates/trace-commons-contributor-ffi/src/lib.rs`
 * (`#[unsafe(no_mangle)] pub unsafe extern "C" fn ...`) exactly; keep the
 * two in sync when either changes.
 *
 * OWNERSHIP RULE, stated once, enforced everywhere in this header: every
 * `char*` RETURNED by this library is owned by the caller and freed with
 * `tc_string_free`. Every `const char*` is BORROWED and valid only until
 * the handle that owns it (`tc_handle*` or `tc_preview*`) is freed. There
 * is no other lifetime rule anywhere in this API.
 *
 * tc_daemon_start returns a tc_handle*; tc_daemon_stop tears the running
 * daemon down but does NOT free that pointer -- a concurrent tc_call /
 * tc_preview_open / tc_subscribe on another thread stays valid and simply
 * observes the daemon as stopped, rather than dereferencing freed memory.
 * tc_handle_free is the only function that reclaims it, and -- like every
 * free function here -- must not be called concurrently with any other
 * call still using the same pointer, and must be called from a plain
 * thread, never from inside a tc_subscribe callback (see its own doc for
 * why). In particular, tc_handle_free must NOT be called concurrently with
 * tc_daemon_stop: tc_daemon_stop does not free the handle, but it also does
 * not hold it against a concurrent free, and tc_handle_free performs its own
 * teardown before freeing.
 *
 * tc_daemon_stop is idempotent, but it is NOT a teardown barrier for a
 * SECOND CONCURRENT CALLER. If two threads call it at once, one thread
 * performs the teardown and blocks until it completes; the other returns
 * IMMEDIATELY, possibly while the daemon is still stopping. Do not treat a
 * tc_daemon_stop return on thread B as proof that thread A's teardown
 * finished. (An earlier revision made the second caller wait; that was
 * unsound -- if the winning caller was tc_handle_free it freed the very lock
 * the waiter had to re-acquire, and a waiter parked on one of the daemon
 * runtime's own worker threads could deadlock the teardown it was waiting
 * for. A weaker honest guarantee is better than a stronger false one.)
 *
 * Every function here catches Rust panics at the boundary and converts them
 * to an ordinary error; a panic never unwinds into the caller. Every
 * pointer parameter is null-checked; passing NULL produces an error, not a
 * crash. No path, token, URL, or trace content ever appears in a string
 * this library returns -- fixed labels only, the same discipline the
 * daemon's socket already applies. Preview content specifically fails
 * outright, rather than being silently edited, if it cannot be represented
 * as a NUL-terminated C string.
 *
 * Every free function (tc_handle_free, tc_preview_free, tc_string_free)
 * detects a double free or a pointer of the wrong kind (e.g. a tc_handle*
 * passed to tc_preview_free) and refuses rather than acting on it --
 * recording a fixed label via tc_last_error and leaking the pointer, which
 * is the only safe response once a raw pointer's type cannot be trusted.
 *
 * SUBSCRIPTION LIFETIME: tc_daemon_stop does NOT end a subscription and is
 * NOT a synchronization point for one -- it only sets a flag a
 * subscription's background task polls at most every 250ms, and an event
 * already buffered when tc_daemon_stop was called can still be delivered in
 * that window. A tc_subscribe callback can be invoked, using ctx, well
 * after tc_daemon_stop has returned to its caller. tc_unsubscribe is the
 * ONLY function that guarantees no further callback invocation once it
 * returns; ctx must remain valid until tc_unsubscribe returns, full stop.
 */

#ifndef TRACE_COMMONS_H
#define TRACE_COMMONS_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Opaque handle to a running daemon, returned by tc_daemon_start. */
typedef struct tc_handle tc_handle;

/* Opaque handle to one open preview, returned by tc_preview_open. */
typedef struct tc_preview tc_preview;

/* Lifecycle. Runs the daemon loop on its own thread with its own runtime.
 *
 * Returns NULL and sets *err (if err is non-NULL) on failure -- most
 * notably when another daemon already holds daemon.lock for this
 * config_dir. A second tc_daemon_start against the same directory must
 * fail rather than let two loops race the same on-disk queue. *err, on
 * failure, is an owned string; free it with tc_string_free.
 */
tc_handle*  tc_daemon_start(const char* config_dir, char** err);

/* Stop the daemon loop. Idempotent, and safe to call from any thread --
 * including from inside a tc_subscribe callback -- and safe to call
 * concurrently with tc_call / tc_preview_open / tc_subscribe on other
 * threads. Does NOT free the handle; call tc_handle_free once nothing else
 * will use it again. Safe to call with NULL.
 *
 * Idempotent, but NOT a teardown barrier for a second concurrent caller:
 * of two simultaneous callers, one performs the teardown and the other
 * returns immediately, possibly before the daemon has finished stopping.
 * And do NOT call tc_handle_free concurrently with this function. Both
 * rules, and why, are spelled out at the top of this header.
 *
 * Is NOT a synchronization point for tc_subscribe callbacks -- see
 * SUBSCRIPTION LIFETIME above and tc_unsubscribe below.
 */
void        tc_daemon_stop(tc_handle*);

/* Free a handle. The only function that reclaims what tc_daemon_start
 * returned; tears the daemon down first if tc_daemon_stop was not already
 * called. Safe to call with NULL.
 *
 * MUST be called from a plain thread that is not inside any tokio runtime
 * context -- in particular, never from inside a tc_subscribe callback.
 * handle owns its own async runtime; freeing it from one of that runtime's
 * own worker threads is refused (leaking the handle, recorded via
 * tc_last_error) rather than risking the crash that would otherwise
 * follow.
 */
void        tc_handle_free(tc_handle*);

/* Control. Same request handlers the socket serves, called in-process.
 *
 * Returns a NUL-terminated JSON response; free with tc_string_free. Never
 * returns NULL: a bad handle, method, or params_json produces a JSON error
 * frame (`{"error":{"code":"bad_params",...}}`) rather than a null pointer.
 */
char*       tc_call(tc_handle*, const char* method, const char* params_json);

/* Events. cb is invoked on a background thread with a JSON event frame
 * each time the daemon publishes one, until tc_unsubscribe is called with
 * the returned token. The event_json pointer passed to cb is borrowed for
 * the duration of that one call only; do not retain it. ctx is passed back
 * unchanged and MUST remain valid until tc_unsubscribe returns -- full
 * stop; see SUBSCRIPTION LIFETIME above. tc_daemon_stop returning is NOT
 * sufficient.
 *
 * A gap in delivery (more than 256 events published between polls) is
 * reported to cb as a synthetic `{"event":"lagged","data":{"skipped":N}}`
 * frame rather than silently dropped.
 *
 * Returns 0 on failure (NULL handle, NULL cb, or a stopped daemon) -- 0 is
 * never a valid token. On success, returns a nonzero token for
 * tc_unsubscribe.
 */
uint64_t    tc_subscribe(tc_handle*, void (*cb)(const char* event_json, void* ctx), void* ctx);

/* Cancel a subscription returned by tc_subscribe. Blocks until that
 * subscription's callback is guaranteed to no longer fire before
 * returning -- see SUBSCRIPTION LIFETIME above; this is the only function
 * with that guarantee. A no-op if token is 0 or unknown.
 *
 * MUST be called from a plain thread that is not inside any tokio runtime
 * context -- in particular, never from a subscription's own callback
 * unsubscribing itself: that would block joining a task that can only
 * finish once the very callback frame making the call returns, a permanent
 * hang. Calling from inside a runtime context refuses (a no-op; the token
 * remains valid to retry from a plain thread) and records why via
 * tc_last_error.
 *
 * IMPORTANT for binding authors: that reentrancy check is "am I inside ANY
 * tokio runtime context", which cannot distinguish true reentrancy (a
 * callback unsubscribing itself) from a host that merely happens to call
 * tc_unsubscribe from a thread driving its own, unrelated async runtime.
 * The latter is refused too -- and because this function returns void, the
 * refusal is SILENT. A host that assumes success there would free ctx while
 * the subscription is still live, believing the API's only barrier had
 * held. Therefore: after every tc_unsubscribe, check tc_last_error. A
 * non-NULL, non-stale value means the call was refused and the barrier did
 * NOT hold -- retry from a plain thread with no runtime context before
 * freeing ctx. Clear or note the prior tc_last_error value first so a
 * leftover error is not mistaken for this one.
 */
void        tc_unsubscribe(tc_handle*, uint64_t token);

/* Preview. Reads the session file and runs the real redaction pipeline.
 *
 * tc_preview_open returns NULL and sets *err (if err is non-NULL) on
 * failure -- most commonly an unknown entry_id, or (deliberately) a
 * redacted body that cannot be represented as a NUL-terminated C string.
 * On success, everything returned by the tc_preview_* accessors below is
 * borrowed and valid until tc_preview_free.
 */
tc_preview* tc_preview_open(tc_handle*, const char* entry_id, char** err);
const char* tc_preview_body(const tc_preview*);          /* redacted transcript, UTF-8 */
const char* tc_preview_summary_json(const tc_preview*);  /* counts, sizes, opening prompt */

/* Search the redacted body for needle, a local in-memory scan. Matches are
 * non-overlapping, left-to-right, and reported as UTF-8 BYTE offsets (not
 * character offsets). An empty needle matches nothing.
 *
 * Returns the number of matches, or -1 on error (including a match count
 * that would overflow a 32-bit count -- reported as an error, never
 * silently truncated). On success, *matches_json is set to an owned JSON
 * array of byte offsets; free with tc_string_free. On error, *matches_json
 * (if non-NULL) is set to NULL -- there is nothing to free.
 */
int32_t     tc_preview_search(const tc_preview*, const char* needle, char** matches_json);

/* Free a preview handle. Safe to call with NULL. Invalidates every
 * const char* previously returned by tc_preview_body /
 * tc_preview_summary_json for this handle.
 */
void        tc_preview_free(tc_preview*);

/* Free a string returned by this library. Safe to call with NULL. This is
 * the only valid way to free a char* this library returns.
 */
void        tc_string_free(char*);

/* The last error recorded on the calling thread, or NULL if none has been
 * recorded yet. Borrowed: valid until the next call, on this same thread,
 * to any function in this library that records a new error. Do not free
 * the returned pointer.
 */
const char* tc_last_error(void);

#ifdef __cplusplus
}
#endif

#endif /* TRACE_COMMONS_H */
